version: '3.7'
services:
  db:
    container_name: charity_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: charity_database
    build:
      context: .
      dockerfile: docker/Dockerfile.db
    ports:
      - "5433:5433"
    networks:
      - local-network
#    platform: linux/amd64

  front:
    build:
      context: .
      dockerfile: docker/Dockerfile.front
    networks:
      - local-network
    ports:
      - "8080:8080"
    #    volumes:
    #      - ./front/nginx.conf:/etc/nginx/conf.d/default.conf
    #      - ./front:/usr/share/nginx/app
#    platform: linux/amd64

  back:
    build:
      context: .
      dockerfile: docker/Dockerfile.back
    container_name: back
    networks:
      - local-network
    environment:
      "ConnectionStrings__Postgres" : "Host=db;Port=5432;User Id=postgres;Password=postgres;Database=charity_database;"
    ports:
      - "80:80"
    depends_on:
      - db
#    platform: linux/amd64

networks:
  local-network:
    driver: bridge