FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dotnet-build
COPY /backend /backend
RUN dotnet publish "/backend/WebLayer/WebLayer.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=dotnet-build /app/publish .

ENTRYPOINT ["dotnet", "WebLayer.dll"]